name: Test RADAR API

on:
  push:
    branches: [main]
    paths:
      - 'tests/**'
      - '.github/workflows/newman-tests.yml'

  schedule:
    - cron: '0 12 * * 1,3,5'

  workflow_dispatch:
jobs:
  APIDockerImage:
    name: Testing Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test API
        run: ./run_tests.sh

      - name: Overwrite file
        uses: 'DamianReeves/write-file-action@master'
        with:
          path: /output/index.html
          write-mode: overwrite

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'

      # - name: Upload Newman HTML results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: results-report
      #     # path: /output/index.html
      #     path: ${{ github.workspace }}/docs/index.html
