name: Test RADAR API

on:
  push:
    branches: [main]
    paths:
      - 'tests/**'
      - '.github/workflows/newman-tests.yml'

  schedule:
    - cron: '0 12 * * 1,3,5'

  workflow_dispatch:
jobs:
  APIDockerImage:
    name: Testing Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Test API
        run: ./run_tests.sh
